### ISSUE TITLE
async is now a keywordand breaks pylama in Python 3.7

### ISSUE THREAD

**Issue by kura** [klen/pylama#123]
pylama has an argparse option called `async`, in Python 3.7 async is now a keyword,

Line 10 of of `main.py` throws an error

```python
from .async import check_async
```

and line 46

```python
if options.async:
```

and finally line 202 of `config.py`

```python
if options.async and 'pylint' in options.linters:
```

are three references I found that caused pylama to break for me on Python 3.7. I don't use the `--async` option so I just removed all those references locally to hack in a fix.

**Comment by susam** [comment]
I have merged @michael-k's pull request #120 into [Pylava](https://github.com/pyfocus/pylava). Pylava is intended to be a community maintained fork of Pylama. It works with Python 3.7.

Enter the following command to install Pylava:

    pip install pylava

With Python 3, you may need to enter the following command instead:

    pip3 install pylava

After that you need to use `pylava` instead of `pylama`, for example, by updating your `pylama` commands to `pylava` commands.

Thanks to @michael-k for the pull request.
