### ISSUE TITLE
pydocstyle version 2 compatibility

### ISSUE THREAD

**Issue by cemsbr** [klen/pylama#96]
```WARNING:root:Linter `pydocstyle` not found.```

This is happening since pydocstyle 2.0.0 released in 2017-04-18.

**Comment by not-raspberry** [comment]
https://github.com/PyCQA/pydocstyle/commit/13159ede09bc67c939493b150a8e3ecfa525b6fc#diff-2031238ddd3b79ef5acbb2277c140700L6

**Comment by not-raspberry** [comment]
Diff (of pylama/lint/pylama_pydocstyle.py) required to make it work, with no backwards compatibility:

```
3c3
< from pydocstyle import PEP257Checker
---
> from pydocstyle import ConventionChecker
25c25
<         } for e in PEP257Checker().check_source(code, path)]
---
>         } for e in ConventionChecker().check_source(code, path, ignore_decorators=None)]
```

@klen Do you want me to create a PR? With or without backwards compatibility?

**Comment by diraol** [comment]
@not-raspberry I've made a PR to fix this (and also considering backwards compatibility), but it raised lots of new errors on the CI. I'm not sure if these errors are related to the new `pydocstyle` version.

It may also have some problem related to the new version of pylint, since that a similar warning was raised after fixing the `pydocstyle` warning (`pylama/config.py WARNING:root:Linter `pylint` not found`).

Any tips on how to fix this things? 

Should I fix `pydocstyle` and `pycodestyle`  erros on `test_pylama.py` or `dummy.py`?

**Comment by colinmcintosh** [comment]
This seems to be an open issue still for Pylama 7.3.3. Is there a workaround for this issue to get pydocstyle to work in Pylama? If there is no workaround can the version of pydocstyle be pinned to a compatible version rather than using `>=2.0.0` in requirements.txt?

**Comment by diraol** [comment]
@colinmcintosh I've made a PR (#97) that may fix this issue. But, for that PR to work (pass on tests), pylama needs to drop python2.6 support (as seen on #98).

**Comment by Deimos** [comment]
I'm going to ping @klen in case he doesn't automatically get notifications of issues on this repo. @klen - pylama has been incompatible with the current version of pydocstyle for over a month now.

**Comment by colinmcintosh** [comment]
@diraol I saw that PR but until someone has time to make the changes needed for it we would appreciate a bugfix release of Pylama that is pinned to version 1.1.1 of pydocstyle.

**Comment by diraol** [comment]
@colinmcintosh My PR solves the problem (off course it drop python 2.6 compatibility, but I think there is no much sense to keep it anymore).

I could also have sent another PR just pinning pydocstile to `1.1.1`, but the problem is that we depend on a feedback from the project owner, no matter the solution or the PR. So our hands are tied over here.
